MvcUser/Models/User/User.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MvcUser.Models
{
    public class User
    {
        public string FirstName { get; set; }
        public string Surname { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime Started { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime? Left { get; set; }
    }
}

MvcUser/Models/Users/Users.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MvcUser.Models
{
    public class Users
    {
        public List<User> UserList { get; set; }
    }
}

MvcUser/Controllers/LookupController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MvcUser.Models;
using System.Net;
using System.IO;
using Newtonsoft.Json;
using System.Text.RegularExpressions;
using System.Net.Http;
using System.Threading.Tasks;

namespace MvcUser.Controllers
{
    public class LookupController : Controller
    {
        private readonly UserAPISettings _MvcUserAPISettings;

        public LookupController(IOptions<UserAPISettings> options)
        {
            _MvcUserAPISettings = options.Value;
        }

        [Route("/Users")]
        [HttpGet("{filter}")]
        public async Task<IActionResult> Users(string filter)
        {
            Users users = new Users();

            if (string.IsNullOrEmpty(filter))
            {
                ModelState.AddModelError("", "A Surname to search for must be entered.");
                users.UserList = new List<User>();
                return View(users);
            }

            Regex r = new Regex("^[a-z ,.'-]+$", RegexOptions.IgnoreCase); // a valid surname regex
            Match m = r.Match(filter);
            if (!m.Success)
            {
                ModelState.AddModelError("", "An invalid Surname was entered, please only use alphabetic, space, dash, comma, period or apostrophe characters.");
                users.UserList = new List<User>();
                return View(users);
            }

            // typically routing would resolve the URI in the same service but this is a separate service currently embedded in the same project.
            // As a separate service it would need config to determine the API URI.
            string URI = _MvcUserAPISettings.URI + "/Users/" + filter; 

            using (var httpClient = new HttpClient())
            {
                var response = await httpClient.GetAsync(URI);

                response.EnsureSuccessStatusCode();

                HttpContent content = response.Content;

                string json = await response.Content.ReadAsStringAsync();

                users.UserList = JsonConvert.DeserializeObject<List<User>>(json);
            }

            if (users.UserList.Count == 0)
            {
                ModelState.AddModelError("", $"No search results for '{filter}'.");
            }

            return View(users);
        }
    }
}

MvcUser/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcUser.Data;
using System.Security.Cryptography.X509Certificates;

namespace MvcUser.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class UsersController : ControllerBase
    {
        private readonly UserDbContext _context;

        public UsersController(UserDbContext context)
        {
            _context = context;
        }

        // GET: api/Users/Filter
        [HttpGet("{filter}")]
        public async Task<ActionResult<IEnumerable<User>>> GetUsers(string filter)
        {
            return await _context.Users.Where(x => x.Surname.Contains(filter)).ToListAsync();
        }
    }
}

MvcUser/Views/Lookup/Users.cshtml
@model MvcUser.Models.Users
<h3>User details lookup</h3>
<p>
    @using (Html.BeginForm("Users", "Lookup", FormMethod.Post))
    {
        @Html.ValidationSummary(false)
        <text>Search:&nbsp;</text><input maxlength="15" type="text" value="" name="filter" />
        <button type="submit">Search</button>
    }
</p>
@if (Model.UserList.Count == 0)
{
    <p>Enter an entire Surname or part of a Surname and press the Search button to see any matching details.</p>
}
else
{
    <table>
        <thead>
            <tr>
                <th style="width:100px;">Name</th>
                <th style="width:100px;">Surname</th>
                <th style="width:100px;">Started</th>
                <th style="width:100px;">Left</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model.UserList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => user.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(x => user.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(x => user.Started)
                    </td>
                    <td>
                        @{
                            var left = user.Left == DateTime.MinValue ? string.Empty : user.Left.Value.ToString("dd MMM yyyy");
                        }
                        @left
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

MvcUser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>User Lookup</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css"><!-- Taken from MS Asp.net demo -->
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>